package corejava;

public class ExceptionEx {

	public static void main(String[] args) {

		int a=5, b=0, c;
		 c=a/b;
		
		System.out.println(c);// it is an arithmetic exception-->anything is divisible by 0 is infinity so i am using try catch
		//this is a runtime exception
	}

}
